server:
  port: 8080

spring:
  application:
    name: eureka-server
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/employee/**
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false